apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-cdc
  namespace: tkn
spec:
  workspaces:
    - name: source  
  volumes:
    - name: docker-config
      secret:
        secretName: acr-secret
        items:
          - key: .dockerconfigjson
            path: config.json

  steps:
    - name: debug
      image : alpine
      script: |
        echo "Debugging workspace contents"
        ls -la $(workspaces.source.path)/repo
    - name: build-cdc
      image: gcr.io/kaniko-project/executor
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
      args:
         - "--dockerfile=$(workspaces.source.path)/repo/cdc-feed/Dockerfile"
         - "--context=$(workspaces.source.path)/repo/cdc-feed"
         - "--destination=antdemoacr.azurecr.io/cdc-feed:latest"           
       