apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cdc-pipeline-run
  namespace: tkn-demo
spec:
  pipelineRef:  
    name: cdc-pipeline
  taskRunTemplate:
    serviceAccountName: sa
  params:
     - name: repo-url
       value: "https://github.com/Ajithindrajith/tekton.git"

  workspaces:
     - name: source    
       volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi