replicaCount: 1

image:
  repository: antdemoacr.azurecr.io/backend
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer   # 🔥 change this
  port: 80

cosmos:
  secretName: cosmos-secret
  key: COSMOS_KEY

keyVault:
  secretProviderClass: cosmos-kv-secret