apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-chart.fullname" . }}
  labels:
    {{- include "front-chart.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "front-chart.name" . }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "front-chart.name" . }}

    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1        # start 1 new pod before killing old
          maxUnavailable: 0
      containers:
        - name: front
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 80

          env:
            - name: Cosmos__Key
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cosmos.secretName }}
                  key: {{ .Values.cosmos.key }}

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.keyVault.secretProviderClass }}