apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-backend-pipeline-run
  namespace: tkn

spec:
  pipelineRef:
    name: build-backend-pipeline

  taskRunTemplate:
    serviceAccountName: sa   # ✅ Correct placement

  params:
    - name: repo-url
      value: "https://github.com/Ajithindrajith/tekton.git"

  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi